server:
  servlet:
    context-path: /stream
  port: 7000
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  http:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB